### PR TITLE
Verification of beacons using noble/bls12-381

### PR DESCRIPTION
**Pull request by CluEleSsUK**
- removed go wasm bindings
- added some recommended limitations on engines and browsers in the
  package.json
- updated standard linter to recognise `BigInt`
- added an action for fixing linting issues
- removed go build steps

### CODE REVIEW

**Comment by CluEleSsUK** [comment]
Currently using the `drand-client` involves some manual copy and loading of the go-built wasm bindings.  
A positive of this is that they're pretty fast and there's some easy alignment with code in the main drand repo.
A drawback is that it creates a few hoops for any consumers of the library to go through in using it. 

In this PR I tried tearing out the go parts to see how it would look and if it's something we might want to consider in the interests of easier adoption.
This should work out of the box with e.g. [create-react-app](https://create-react-app.dev/) without having to load the wasm files manually.

Additionally, we could provide multiple builds should users want to opt for a more performant version.

**Comment by CluEleSsUK** [comment]
A question worth considering before merging this - should it be a major version bump? It doesn't break the interface per se but it changes the interaction pattern

**Comment by AnomalRoil** [comment]
I'm fine with bumping the major version on my side.

**Comment by CluEleSsUK** [comment]
Gonna make a few more changes then aggregate them into a major version bump

**Pull request merged**
