### PR TITLE
Fix the `roundTime` method (broken after typescript migration)

### PR DESCRIPTION
**Pull request by very-lame-username**
During the typescript migration, the [`roundTime` method](https://github.com/drand/drand-client/blob/bdfdb7a64c52862f7b6353b851bddd9f1b589e7f/lib/chain.ts#L25) was changed from this:

```js
/**
   * roundTime determines the time a round should be available, given a chain
   * genesis and a chain period.
   *
   * @param round {number} Round number
   * @param genesis {number} Chain genesis time in ms
   * @param period {number} Chain period in ms
   */
  static roundTime (round, genesis, period) {
    round = round < 0 ? 0 : round
    return genesis + ((round - 1) * period)
  }
```
to this:
```ts
/**
     * roundTime determines the time a round should be available, given a chain
     * genesis and a chain period.
     *
     * @param round {number} Round number
     * @param genesis {number} Chain genesis time in seconds
     * @param period {number} Chain period in seconds
     */
    static roundTime (round: number, genesis: number, period: number) {
        round = round < 0 ? 0 : round
        return genesis + ((round - 1) * period) * 1000
    }
}
```

As the method now receives times in seconds, the result should be multiplied by 1000, but the genesis was not included in this multiplication. As such, the returned value is far too low.

The tests for `chain.ts` did not catch this as they all used a genesis of 0.

This bug also breaks `Client.watch` as the value passed to `waitOrAbort` is negative, thus making it repeatedly get the same round. I've changed `drand.test.ts` to make the watch test check if it finished too early.

This PR fixes the `roundTime` method by moving the parentheses, adds extra tests for `roundTime`, and modifies one test in `drand.test.ts`.

### CODE REVIEW

**Review by CluEleSsUK — APPROVED** [review]
Great catch, thanks! The linter is complaining but it should be a small fix - otherwise lgtm!

**Comment by CluEleSsUK** [comment]
Just a small note that the typescript migration isn't live on npm yet; we're planning to bundle a few changes and cut a 1.0.0 release early next month along with some changes relating to [unchained randomness](https://drand.love/docs/cryptography/#randomness)

**Comment by very-lame-username** [comment]
Awesome, I've fixed the linter issue, it should be good to go.

**Comment by CluEleSsUK** [comment]
Ah hmm, I just noticed the npm deploy action can't read secrets for accounts without write access - lemme quickly add a workaround

**Comment by CluEleSsUK** [comment]
Just waiting on an approval for https://github.com/drand/drand-client/pull/36 - sorry for the delay!

**Comment by CluEleSsUK** [comment]
Okay it's merged, if you pull latest it should be good to rock!

**Comment by very-lame-username** [comment]
Done.

**Comment by CluEleSsUK** [comment]
Ahhh sorry to make you jump through another hoop but could you possibly sign your commits?
If you have PGP key already configured on your github profile, you can just run `git rebase --exec 'git commit --amend --no-edit -n -S' -i HEAD~1` and it should all work

**Comment by very-lame-username** [comment]
No problem, I've signed and rebased the last 4 commits.

**Comment by CluEleSsUK** [comment]
Good to go!

**Review by AnomalRoil — APPROVED** [review]
LGTM

**Pull request merged**
